### ISSUE TITLE
error when unenroling manual enroled user

### ISSUE THREAD

**Issue by ewallah** [dasistwas/moodle-mod_newsletter#20]
Debugging: Can not execute event observer 'mod_newsletter_observer::role_assigned'
Can not execute event observer 'mod_newsletter_observer::user_enrolment_deleted'
line 164 of /lib/classes/event/manager.php: call to debugging()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 721 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 1500 of /lib/enrollib.php: call to core\event\base->trigger()
line 69 of /enrol/unenroluser.php: call to enrol_plugin->unenrol_user()

Reproduce:
1. Manual enrol user
2. Wait cron execution
3. Unenrol user : /enrol/unenroluser.php?id=X&page=0&perpage=100&sort=lastname&dir=ASC&newcourse&ue=Y

Moodle 2.9.2+

**Comment by dasistwas** [comment]
Hi,

thank you for reporting this bug. Apparently you must not use namespaces in observers.

Fixed in https://github.com/dasistwas/moodle-mod_newsletter/commit/b1740bdb426e96dda1729878fecd8794ab95bf09

Kind regards,
David
