### ISSUE TITLE
cron errors

### ISSUE THREAD

**Issue by ewallah** [dasistwas/moodle-mod_newsletter#21]
I only got cron working after doing some modifications :

lib.php:
--require_once( 'cron_helper.php');
++require_once($CFG->dirroot . '/mod/newsletter/cron_helper.php');
cron_helper::lock();
--require_once( 'locallib.php');
++require_once($CFG->dirroot . '/mod/newsletter/locallib.php');
cron_helper.php
--$lock_file = NEWSLETTER_LOCK_DIR . '/' . $argv[0] . NEWSLETTER_LOCK_SUFFIX;
++$lock_file = NEWSLETTER_LOCK_DIR . '/' . NEWSLETTER_LOCK_SUFFIX;

Moodle 2.9.2+

**Comment by dasistwas** [comment]
Hi,
thank you for pointing out the problems. Should be solved with:
https://github.com/dasistwas/moodle-mod_newsletter/commit/fb45cb708f75db13f0267096857dcd7c38ff0155

Kind regards,
David
