### ISSUE TITLE
Jenkins - syntax error for PHP 7

### ISSUE THREAD

**Issue by nitro2010** [dasistwas/moodle-mod_newsletter#22]
> 19:18:42 No syntax errors detected in /opt/lampp/htdocs/moodle/mod/newsletter/cssparser/Value/URL.php
19:18:43 PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /opt/lampp/htdocs/moodle/mod/newsletter/cssparser/Value/String.php on line 5
19:18:43 
19:18:43 Fatal error: Cannot use 'String' as class name as it is reserved in /opt/lampp/htdocs/moodle/mod/newsletter/cssparser/Value/String.php on line 5
19:18:43 Errors parsing /opt/lampp/htdocs/moodle/mod/newsletter/cssparser/Value/String.php

Fix:
- change name class 'String' to 'cString' in String.php
- change in file 'Parser.php':
- from use Sabberworm\CSS\Value\String; to use Sabberworm\CSS\Value\cString;
- from return new String($sResult); to return new cString($sResult);

please see:

https://github.com/nitro2010/moodle/blob/MOODLE_30/mod/newsletter/cssparser/Parser.php

Regards

**Comment by dasistwas** [comment]
Hi,

thank you for reporting this issue and providing a fix. Just fixed it in the master branch.

Kind regards,
David
