### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by behoof** [dasistwas/moodle-mod_newsletter#28]
Thanks for this plugin. Really useful!

One wish: translating the subscribe/unsubscribe link. 

The mod_newsletter|subscribe (and unsubscribe) doesn't contain variables.

Bert

**Comment by michaelpollak** [comment]
Hello Bert, thank you for your feedback.
In the language files you should find the string 'unsubscribe_link_text' which stores the string used during the creation of the unsubscribe link.
What language do you use, maybe we could collaborate on a specific translation?

**Comment by dasistwas** [comment]
Not sure what you mean exactly. I just checked the module and did not find any hard coded language string for the subscribe link. But it is possible, that it is not yet translated.
