### ISSUE TITLE
Version number inccorrect format

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_newsletter#37]
Version number has incorrect forma in version.php. Too many digitst!!!! Please be careful, that messes up a lot. You have to change your database now in correct the version number directly there to something like
2018060600

**Comment by dasistwas** [comment]
you have to change newsletter_version in table config_plugins in order to be able to upgrade again on your test system

**Comment by michaelpollak** [comment]
Sorry for the typo and thank you for fixing it.
