### ISSUE TITLE
Wrong link in email sent after successful unsubscription

### ISSUE THREAD

**Issue by salex-uriel** [dasistwas/moodle-mod_newsletter#42]
Hi,
At the end of the email there is a re-subscription link, but its url is incomplete: 

> Dear bla bla,
> You were successfully unsubscribed from the newsletter news. If you did this on purpose, there is nothing more to do. If you did accidentally unsubscribe, you can resubscribe now under the following link:
> https://www.yoursite/mod/newsletter/view.php?id

Class file: **newsletter.php**
Function: **get_url()**
Variable: **$url** must be:
`$url = new moodle_url('/mod/newsletter/view.php',
                array(NEWSLETTER_PARAM_ID => $this->get_course_module()->id,
                NEWSLETTER_PARAM_ACTION => NEWSLETTER_ACTION_SUBSCRIBE));`

**Comment by dasistwas** [comment]
Thank you, will fix.

**Comment by dasistwas** [comment]
The issue should be fixed by the latest commit.
